title: William Bernardoni's Personal Page
email: wrb37@case.edu
author: William Bernardoni
url: https://wrbernardoni.github.io/
description: >-
  The personal page of William Bernardoni.
  Here you can find my papers, research, and mathematical thoughts!
twitter_username: billy.bernardon1
github_username: wrbernardoni

future: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag